#!/usr/bin/env bash
# Render apps.conf into per-domain nginx server blocks under generated/conf.d/,
# then validate the result with `nginx -t` before anyone tries to serve it.
#
# A domain gets an HTTPS block only once its certificate exists, so a brand new
# app is reachable over HTTP (and can answer ACME challenges) immediately, then
# upgrades itself on the next run once ensure-certs.sh has issued its cert.
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

# Emits the shared "server level" extras: the per-app snippet if one exists and
# the rate limit if the app asked for it.
emit_extras() {
    local domain=$1 flags=$2
    if extra_snippet "$domain"; then
        echo "    include /etc/nginx/snippets/extra-$domain.conf;"
    fi
    if has_flag "$flags" ratelimit; then
        echo "    limit_req zone=general burst=20 nodelay;"
    fi
}

emit_location() {
    local upstream=$1 flags=$2
    echo "    location / {"
    # Going through a variable forces per-request DNS resolution, so a restarted
    # app container does not leave nginx pointing at a stale IP.
    echo "        set \$upstream $upstream;"
    echo "        proxy_pass http://\$upstream;"
    echo "        include /etc/nginx/snippets/proxy-headers.conf;"
    if has_flag "$flags" websocket; then
        echo "        include /etc/nginx/snippets/proxy-websocket.conf;"
    fi
    echo "    }"
}

echo "🧱 Generating nginx configuration from apps.conf..."

# Clear the directory's contents rather than the directory itself. It is
# bind-mounted into the nginx container, so replacing the directory inode
# would leave the running container looking at the deleted one -- the host
# would show the new config while nginx saw an empty conf.d.
mkdir -p "$GENERATED_DIR"
rm -f "$GENERATED_DIR"/*.conf

# Catch-all, so a request for an unknown hostname is refused rather than being
# silently served by whichever app happens to sort first.
cat > "$GENERATED_DIR/00-default.conf" <<'EOF'
# Generated by scripts/generate-config.sh -- do not edit.
server {
    listen 80 default_server;
    server_name _;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 444;
    }
}

server {
    listen 443 ssl default_server;
    ssl_reject_handshake on;
}
EOF

count=0
while read -r domain upstream health flags; do
    : "${health:=/}"
    : "${flags:=-}"
    count=$((count + 1))

    {
        echo "# Generated by scripts/generate-config.sh from apps.conf -- do not edit."
        echo "# $domain -> $upstream (health: $health, flags: $flags)"
        echo
        echo "server {"
        echo "    listen 80;"
        echo "    server_name $domain;"
        echo
        echo "    location /.well-known/acme-challenge/ {"
        echo "        root /var/www/certbot;"
        echo "    }"
        echo

        if cert_exists "$domain"; then
            echo "    location / {"
            echo "        return 301 https://\$host\$request_uri;"
            echo "    }"
            echo "}"
            echo
            echo "server {"
            echo "    listen 443 ssl;"
            echo "    http2 on;"
            echo "    server_name $domain;"
            echo
            echo "    ssl_certificate /etc/letsencrypt/live/$domain/fullchain.pem;"
            echo "    ssl_certificate_key /etc/letsencrypt/live/$domain/privkey.pem;"
            echo "    include /etc/nginx/snippets/ssl-params.conf;"
            echo
            echo "    include /etc/nginx/snippets/security-headers.conf;"
            extras="$(emit_extras "$domain" "$flags")"
            if [ -n "$extras" ]; then
                echo "$extras"
            fi
            echo
            emit_location "$upstream" "$flags"
            echo "}"
        else
            # No certificate yet: serve the app over plain HTTP so it still works
            # while DNS propagates and ensure-certs.sh does its thing.
            extras="$(emit_extras "$domain" "$flags")"
            if [ -n "$extras" ]; then
                echo "$extras"
                echo
            fi
            emit_location "$upstream" "$flags"
            echo "}"
        fi
    } > "$GENERATED_DIR/$domain.conf"

    if cert_exists "$domain"; then
        echo "   ✅ $domain -> $upstream (https)"
    else
        echo "   ⏳ $domain -> $upstream (http only, no certificate yet)"
    fi
done < <(apps)

if [ "$count" -eq 0 ]; then
    echo "❌ apps.conf lists no applications" >&2
    exit 1
fi

if [ "${SKIP_VALIDATE:-0}" = "1" ]; then
    echo "⏭️  Skipping nginx -t (SKIP_VALIDATE=1)"
    exit 0
fi

echo "🔍 Validating generated configuration..."
mounts=(
    -v "$REPO_ROOT/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    -v "$REPO_ROOT/nginx/snippets:/etc/nginx/snippets:ro"
    -v "$GENERATED_DIR:/etc/nginx/conf.d:ro"
)
# Only mount the certificate directory when it exists, so validating on a laptop
# does not conjure a root-owned certbot/ directory out of nowhere.
if [ -d "$CERT_DIR" ]; then
    mounts+=(-v "$CERT_DIR:/etc/letsencrypt:ro")
fi

docker run --rm "${mounts[@]}" nginx:alpine nginx -t
echo "✅ Configuration is valid"
